server:
  port: 8888
  tomcat:
    max-http-post-size: 20000
spring:
  application:
    name: blog
  aop:
    auto: true
  datasource:
    url: jdbc:mysql://39.106.89.216:3330/ivan_blog?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 135555
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  resources:
    static-locations: classpath:/static
  redis:
    database: 0
    host: 39.106.89.216
    port: 6379
    password: 123456
    timeout: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ivan.blog.model
logging:
  level:
    ssm.app.mapper : debug